/* ============================================================
   quotes.js — 365 Quotes Pilihan untuk Safitri Lailasari
   Pojok Motivasi · Apotek Alpro
   Format: { text, author, category, lang, translation? }
   lang: 'id' | 'ar' | 'en'
   Komposisi: ~250 Indonesia · ~65 Arab/Islami · ~50 Inggris
   ============================================================ */

const QUOTES = [

  // ════════════════════════════════════════
  //  KEBERANIAN (46 quotes)
  // ════════════════════════════════════════

  { text: "Percayalah akan kata hatimu, Allah selalu menuntun jalanmu.", author: "Hendri", category: "Keberanian", lang: "id" },
  { text: "Keberanian bukan berarti tidak takut, tapi tetap melangkah meski takut.", author: "Anonimus", category: "Keberanian", lang: "id" },
  { text: "Langkah pertama selalu yang terberat, tapi juga yang paling bermakna.", author: "Anonimus", category: "Keberanian", lang: "id" },
  { text: "Mereka yang berani jatuh jauh, itulah yang mampu terbang tinggi.", author: "Anonimus", category: "Keberanian", lang: "id" },
  { text: "Satu langkah keberanian hari ini lebih bernilai dari seribu rencana yang tak pernah dijalankan.", author: "Anonimus", category: "Keberanian", lang: "id" },
  { text: "Ketakutan adalah penjara yang kuncinya ada di tanganmu sendiri.", author: "Anonimus", category: "Keberanian", lang: "id" },
  { text: "Beranilah menjadi dirimu sendiri di dunia yang terus mencoba membuatmu menjadi orang lain.", author: "Ralph Waldo Emerson", category: "Keberanian", lang: "id" },
  { text: "Orang yang berani bukan yang tidak pernah jatuh, tapi yang bangkit setiap kali jatuh.", author: "Anonimus", category: "Keberanian", lang: "id" },
  { text: "Keberanian sejati adalah melakukan apa yang perlu dilakukan, meski tidak ada yang melihat.", author: "Anonimus", category: "Keberanian", lang: "id" },
  { text: "Masa depanmu dimulai di ujung zona nyamanmu.", author: "Neale Donald Walsch", category: "Keberanian", lang: "id" },
  { text: "Jangan tunggu sampai tidak takut lagi. Takut tapi tetap melangkah — itulah keberanian.", author: "Anonimus", category: "Keberanian", lang: "id" },
  { text: "Setiap mimpi besar dimulai dari keputusan kecil yang berani.", author: "Anonimus", category: "Keberanian", lang: "id" },
  { text: "Perahu yang berlabuh di pelabuhan memang aman, tapi bukan untuk itulah perahu dibuat.", author: "John A. Shedd", category: "Keberanian", lang: "id" },
  { text: "Kamu lebih berani dari yang kamu percaya, lebih kuat dari yang kamu rasa, dan lebih cerdas dari yang kamu kira.", author: "A.A. Milne", category: "Keberanian", lang: "id" },
  { text: "Keberanian adalah otot — semakin sering dilatih, semakin kuat.", author: "Anonimus", category: "Keberanian", lang: "id" },
  { text: "Jangan biarkan rasa takut mencuri impianmu.", author: "Anonimus", category: "Keberanian", lang: "id" },
  { text: "Mereka yang tidak pernah gagal adalah mereka yang tidak pernah mencoba hal besar.", author: "Anonimus", category: "Keberanian", lang: "id" },
  { text: "Keberanian bukan soal ukuran tubuh, tapi ukuran hati.", author: "Anonimus", category: "Keberanian", lang: "id" },
  { text: "Ambil risiko itu. Jika berhasil, luar biasa. Jika tidak, kamu mendapat pelajaran.", author: "Anonimus", category: "Keberanian", lang: "id" },
  { text: "Dunia ini milik orang-orang yang berani.", author: "Anonimus", category: "Keberanian", lang: "id" },
  { text: "Lebih baik mencoba dan gagal daripada tidak pernah mencoba dan selalu bertanya-tanya.", author: "Anonimus", category: "Keberanian", lang: "id" },
  { text: "Beranilah bermimpi lebih besar dari kemampuanmu hari ini.", author: "Anonimus", category: "Keberanian", lang: "id" },
  { text: "Satu kata yang berani lebih kuat dari seribu kata yang disimpan dalam diam.", author: "Anonimus", category: "Keberanian", lang: "id" },
  { text: "Beranilah memulai, meski belum sempurna.", author: "Anonimus", category: "Keberanian", lang: "id" },
  { text: "Kegagalan bukan akhir dari perjalanan — itu hanya belokan di jalan menuju tujuanmu.", author: "Anonimus", category: "Keberanian", lang: "id" },
  { text: "Berani berbeda adalah awal dari segala perubahan yang bermakna.", author: "Anonimus", category: "Keberanian", lang: "id" },
  { text: "Jangan biarkan pikiran 'bagaimana jika gagal?' menghalangi pertanyaan lebih penting: 'bagaimana jika berhasil?'", author: "Anonimus", category: "Keberanian", lang: "id" },
  { text: "Setiap langkah berani yang kamu ambil menginspirasi orang lain untuk melakukan hal yang sama.", author: "Anonimus", category: "Keberanian", lang: "id" },
  { text: "Tidak ada yang salah dengan jatuh. Yang salah adalah memutuskan untuk tetap di sana.", author: "Anonimus", category: "Keberanian", lang: "id" },
  { text: "Keberanian bukan tentang tidak merasa takut, tapi tentang tidak membiarkan ketakutan menghentikanmu.", author: "Anonimus", category: "Keberanian", lang: "id" },
  { text: "Seorang pemberani bukan yang tidak pernah goyah, tapi yang terus melangkah meski goyah.", author: "Anonimus", category: "Keberanian", lang: "id" },
  { text: "فَإِذَا عَزَمۡتَ فَتَوَكَّلۡ عَلَى ٱللَّهِ", author: "Q.S. Ali Imran: 159", category: "Keberanian", lang: "ar", translation: "Apabila kamu telah membulatkan tekad, maka bertawakallah kepada Allah." },
  { text: "إِنَّ مَعَ ٱلۡعُسۡرِ يُسۡرًا", author: "Q.S. Al-Insyirah: 6", category: "Keberanian", lang: "ar", translation: "Sesungguhnya bersama kesulitan ada kemudahan." },
  { text: "مَن جَدَّ وَجَدَ", author: "Pepatah Arab", category: "Keberanian", lang: "ar", translation: "Barangsiapa bersungguh-sungguh, ia akan berhasil." },
  { text: "وَلَا تَهِنُوا وَلَا تَحۡزَنُوا وَأَنتُمُ ٱلۡأَعۡلَوۡنَ إِن كُنتُم مُّؤۡمِنِينَ", author: "Q.S. Ali Imran: 139", category: "Keberanian", lang: "ar", translation: "Janganlah kamu bersikap lemah dan jangan pula bersedih hati, padahal kamulah orang-orang yang paling tinggi derajatnya jika kamu beriman." },
  { text: "وَمَن يَتَوَكَّلۡ عَلَى ٱللَّهِ فَهُوَ حَسۡبُهُ", author: "Q.S. Ath-Thalaq: 3", category: "Keberanian", lang: "ar", translation: "Dan barangsiapa yang bertawakal kepada Allah, niscaya Allah akan mencukupkan keperluannya." },
  { text: "لَا يُكَلِّفُ ٱللَّهُ نَفۡسًا إِلَّا وُسۡعَهَا", author: "Q.S. Al-Baqarah: 286", category: "Keberanian", lang: "ar", translation: "Allah tidak membebani seseorang melainkan sesuai kesanggupannya." },
  { text: "حَسۡبُنَا ٱللَّهُ وَنِعۡمَ ٱلۡوَكِيلُ", author: "Q.S. Ali Imran: 173", category: "Keberanian", lang: "ar", translation: "Cukuplah Allah menjadi penolong kami dan Allah adalah sebaik-baik pelindung." },
  { text: "الشُّجَاعَةُ أَنْ تَعْرِفَ مَا لَا تَخَافُهُ", author: "Pepatah Arab", category: "Keberanian", lang: "ar", translation: "Keberanian adalah mengetahui apa yang sebenarnya tidak perlu ditakuti." },
  { text: "It always seems impossible until it's done.", author: "Nelson Mandela", category: "Keberanian", lang: "en", translation: "Semua tampak mustahil sampai akhirnya selesai." },
  { text: "The brave may not live forever, but the cautious do not live at all.", author: "Meg Cabot", category: "Keberanian", lang: "en", translation: "Yang berani mungkin tidak hidup selamanya, tapi yang pengecut tidak pernah benar-benar hidup." },
  { text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky", category: "Keberanian", lang: "en", translation: "Kamu pasti gagal di 100% tembakan yang tidak pernah kamu coba." },
  { text: "Fear is only as deep as the mind allows.", author: "Japanese Proverb", category: "Keberanian", lang: "en", translation: "Rasa takut hanya sedalam yang pikiran izinkan." },
  { text: "Be fearless in the pursuit of what sets your soul on fire.", author: "Jennifer Lee", category: "Keberanian", lang: "en", translation: "Jangan takut mengejar hal-hal yang membakar semangatmu." },
  { text: "Courage is not the absence of fear, but the triumph over it.", author: "Nelson Mandela", category: "Keberanian", lang: "en", translation: "Keberanian bukan ketiadaan rasa takut, tapi kemenangan atas rasa takut itu." },
  { text: "She believed she could, so she did.", author: "R.S. Grey", category: "Keberanian", lang: "en", translation: "Dia percaya dia bisa, maka dia pun berhasil." },

  // ════════════════════════════════════════
  //  KETEGUHAN (45 quotes)
  // ════════════════════════════════════════

  { text: "Jangan pernah takut, jangan biarkan apapun mengambil cahaya hidupmu.", author: "Hendri", category: "Keteguhan", lang: "id" },
  { text: "Kesuksesan bukan tentang tidak pernah jatuh, tapi tentang bangkit setiap kali jatuh.", author: "Anonimus", category: "Keteguhan", lang: "id" },
  { text: "Tekad yang kuat mengubah sesuatu yang mustahil menjadi hanya soal waktu.", author: "Anonimus", category: "Keteguhan", lang: "id" },
  { text: "Jika kamu jatuh seribu kali, bangkitlah seribu satu kali.", author: "Pepatah Jepang", category: "Keteguhan", lang: "id" },
  { text: "Batu besar pun terkikis oleh tetesan air yang terus-menerus.", author: "Pepatah", category: "Keteguhan", lang: "id" },
  { text: "Tidak ada jalan pintas untuk tempat mana pun yang layak dituju.", author: "Beverly Sills", category: "Keteguhan", lang: "id" },
  { text: "Keteguhan adalah saat kamu terus bergerak meski tidak ada yang bertepuk tangan.", author: "Anonimus", category: "Keteguhan", lang: "id" },
  { text: "Setiap pejuang pernah lelah. Yang membedakan adalah ia tetap berdiri.", author: "Anonimus", category: "Keteguhan", lang: "id" },
  { text: "Pohon yang kuat tumbuh dari akar yang telah merasakan banyak badai.", author: "Anonimus", category: "Keteguhan", lang: "id" },
  { text: "Bukan tentang seberapa cepat kamu sampai, tapi tentang tidak berhenti sebelum sampai.", author: "Anonimus", category: "Keteguhan", lang: "id" },
  { text: "Orang yang berhasil bukan yang tidak pernah gagal, tapi yang tidak menyerah setelah gagal.", author: "Anonimus", category: "Keteguhan", lang: "id" },
  { text: "Satu-satunya cara untuk gagal adalah berhenti mencoba.", author: "Anonimus", category: "Keteguhan", lang: "id" },
  { text: "Ketika lelah, istirahat — bukan menyerah.", author: "Anonimus", category: "Keteguhan", lang: "id" },
  { text: "Jalan yang sulit seringkali menuju ke tempat yang paling indah.", author: "Anonimus", category: "Keteguhan", lang: "id" },
  { text: "Kesabaran adalah senjata terkuat yang dimiliki orang-orang bijak.", author: "Anonimus", category: "Keteguhan", lang: "id" },
  { text: "Ketekunan adalah kemampuan untuk tetap antusias meski menghadapi kegagalan demi kegagalan.", author: "Anonimus", category: "Keteguhan", lang: "id" },
  { text: "Impian tidak memiliki batas waktu. Selama kamu masih bernapas, masih ada kesempatan.", author: "Anonimus", category: "Keteguhan", lang: "id" },
  { text: "Jangan menyerah hanya karena membutuhkan waktu. Waktu akan berlalu juga, entah kamu menyerah atau tidak.", author: "Anonimus", category: "Keteguhan", lang: "id" },
  { text: "Setiap langkah maju sekecil apapun tetap lebih baik daripada berdiri di tempat.", author: "Anonimus", category: "Keteguhan", lang: "id" },
  { text: "Kegagalan bukan lawan dari kesuksesan — itu adalah bagian dari kesuksesan.", author: "Arianna Huffington", category: "Keteguhan", lang: "id" },
  { text: "Hal-hal terbaik datang kepada mereka yang tidak menyerah.", author: "Anonimus", category: "Keteguhan", lang: "id" },
  { text: "Ketekunan mengalahkan bakat ketika bakat tidak disertai ketekunan.", author: "Anonimus", category: "Keteguhan", lang: "id" },
  { text: "Setiap pagi adalah kesempatan baru untuk memulai lagi.", author: "Anonimus", category: "Keteguhan", lang: "id" },
  { text: "Tanpa perjuangan, tidak ada kemajuan.", author: "Frederick Douglass", category: "Keteguhan", lang: "id" },
  { text: "Bertahan di saat sulit adalah tanda bahwa kamu lebih kuat dari masalahmu.", author: "Anonimus", category: "Keteguhan", lang: "id" },
  { text: "Jangan ukur kemajuanmu dengan kemajuan orang lain.", author: "Anonimus", category: "Keteguhan", lang: "id" },
  { text: "Diamlah sejenak, ambil napas, lalu lanjutkan perjuanganmu.", author: "Anonimus", category: "Keteguhan", lang: "id" },
  { text: "Setiap hari kamu bertahan adalah bukti kamu lebih tangguh dari yang kamu kira.", author: "Anonimus", category: "Keteguhan", lang: "id" },
  { text: "Kamu tidak harus merasa kuat untuk terus melangkah — langkah itulah yang membuatmu kuat.", author: "Anonimus", category: "Keteguhan", lang: "id" },
  { text: "Proses yang panjang tidak pernah sia-sia jika arahnya benar.", author: "Anonimus", category: "Keteguhan", lang: "id" },
  { text: "Yang terlihat lemah seringkali adalah yang paling tangguh di dalam.", author: "Anonimus", category: "Keteguhan", lang: "id" },
  { text: "وَٱصۡبِرۡ وَمَا صَبۡرُكَ إِلَّا بِٱللَّهِ", author: "Q.S. An-Nahl: 127", category: "Keteguhan", lang: "ar", translation: "Dan bersabarlah, kesabaranmu itu tiada lain hanyalah dengan pertolongan Allah." },
  { text: "إِنَّ ٱللَّهَ مَعَ ٱلصَّٰبِرِينَ", author: "Q.S. Al-Baqarah: 153", category: "Keteguhan", lang: "ar", translation: "Sesungguhnya Allah beserta orang-orang yang sabar." },
  { text: "ٱلصَّبۡرُ مِفۡتَاحُ ٱلۡفَرَجِ", author: "Pepatah Arab", category: "Keteguhan", lang: "ar", translation: "Kesabaran adalah kunci kelapangan." },
  { text: "فَإِنَّ مَعَ ٱلۡعُسۡرِ يُسۡرًا", author: "Q.S. Al-Insyirah: 5", category: "Keteguhan", lang: "ar", translation: "Maka sesungguhnya bersama kesulitan ada kemudahan." },
  { text: "مَا أَنْعَمَ اللَّهُ عَلَى عَبْدٍ نِعْمَةً أَعْظَمَ مِنَ الصَّبْرِ", author: "H.R. Bukhari", category: "Keteguhan", lang: "ar", translation: "Tidaklah Allah memberi nikmat kepada seorang hamba yang lebih besar dari nikmat sabar." },
  { text: "ٱلصَّبۡرُ جَمِيلٞ", author: "Q.S. Yusuf: 83", category: "Keteguhan", lang: "ar", translation: "Kesabaran itu indah." },
  { text: "وَبَشِّرِ ٱلصَّٰبِرِينَ", author: "Q.S. Al-Baqarah: 155", category: "Keteguhan", lang: "ar", translation: "Dan sampaikanlah kabar gembira kepada orang-orang yang sabar." },
  { text: "مَنِ اتَّقَى اللَّهَ وَجَدَ مَعَهُ مَخْرَجًا", author: "Q.S. Ath-Thalaq: 2", category: "Keteguhan", lang: "ar", translation: "Barangsiapa bertakwa kepada Allah, niscaya Dia akan mengadakan jalan keluar baginya." },
  { text: "Perseverance is not a long race; it is many short races one after the other.", author: "Walter Elliot", category: "Keteguhan", lang: "en", translation: "Ketekunan bukan satu perlombaan panjang; melainkan banyak perlombaan pendek satu demi satu." },
  { text: "Fall seven times, stand up eight.", author: "Japanese Proverb", category: "Keteguhan", lang: "en", translation: "Jatuh tujuh kali, bangkit delapan kali." },
  { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius", category: "Keteguhan", lang: "en", translation: "Tidak masalah seberapa pelan kamu melangkah, asalkan tidak berhenti." },
  { text: "Strength does not come from winning. Your struggles develop your strengths.", author: "Arnold Schwarzenegger", category: "Keteguhan", lang: "en", translation: "Kekuatan tidak datang dari kemenangan. Perjuanganmu itulah yang membangun kekuatanmu." },
  { text: "A river cuts through rock not because of its power, but because of its persistence.", author: "James N. Watkins", category: "Keteguhan", lang: "en", translation: "Sungai membelah batu bukan karena kekuatannya, tapi karena kegigihannya." },
  { text: "Courage doesn't always roar. Sometimes courage is the quiet voice at the end of the day saying, 'I will try again tomorrow.'", author: "Mary Anne Radmacher", category: "Keteguhan", lang: "en", translation: "Keberanian tidak selalu mengaum. Kadang keberanian adalah suara pelan di akhir hari yang berkata, 'Aku akan mencoba lagi besok.'" },

  // ════════════════════════════════════════
  //  PERTUMBUHAN (44 quotes)
  // ════════════════════════════════════════

  { text: "Hallo Fit, SMILE =), kamu adalah wanita yang berbahagia dan diberkati.", author: "Hendri", category: "Pertumbuhan", lang: "id" },
  { text: "Setiap hari kamu harus memilih antara nyaman atau tumbuh. Kamu tidak bisa memiliki keduanya sekaligus.", author: "Ginni Rometty", category: "Pertumbuhan", lang: "id" },
  { text: "Versi terbaikmu masih sedang dalam proses pembuatan.", author: "Anonimus", category: "Pertumbuhan", lang: "id" },
  { text: "Kamu tidak perlu sempurna untuk mulai, tapi kamu harus mulai untuk menjadi sempurna.", author: "Anonimus", category: "Pertumbuhan", lang: "id" },
  { text: "Perubahan adalah harga yang harus dibayar untuk tumbuh.", author: "Anonimus", category: "Pertumbuhan", lang: "id" },
  { text: "Orang yang tidak pernah membuat kesalahan tidak pernah mencoba hal baru.", author: "Albert Einstein", category: "Pertumbuhan", lang: "id" },
  { text: "Ketidaknyamanan adalah guru terbaik pertumbuhanmu.", author: "Anonimus", category: "Pertumbuhan", lang: "id" },
  { text: "Setiap versi dirimu yang baru tumbuh dari setiap kesulitan yang berhasil kamu lewati.", author: "Anonimus", category: "Pertumbuhan", lang: "id" },
  { text: "Jangan takut berubah. Kupu-kupu pun harus melewati kepompong yang gelap sebelum bisa terbang.", author: "Anonimus", category: "Pertumbuhan", lang: "id" },
  { text: "Belajarlah dari kemarin, hiduplah hari ini, berharaplah untuk hari esok.", author: "Albert Einstein", category: "Pertumbuhan", lang: "id" },
  { text: "Setiap kali kamu belajar sesuatu yang baru, kamu menjadi orang baru.", author: "Anonimus", category: "Pertumbuhan", lang: "id" },
  { text: "Pertumbuhan dimulai ketika kamu mulai bertanya, bukan ketika kamu merasa sudah tahu.", author: "Anonimus", category: "Pertumbuhan", lang: "id" },
  { text: "Investasi terbaik yang bisa kamu lakukan adalah investasi pada dirimu sendiri.", author: "Warren Buffett", category: "Pertumbuhan", lang: "id" },
  { text: "Kamu adalah penjumlahan dari semua pelajaran yang pernah kamu pelajari.", author: "Anonimus", category: "Pertumbuhan", lang: "id" },
  { text: "Gagal adalah pengalaman yang paling mahal dan juga paling berharga.", author: "Anonimus", category: "Pertumbuhan", lang: "id" },
  { text: "Setiap hari adalah halaman baru dalam buku kehidupanmu. Tuliskan dengan baik.", author: "Anonimus", category: "Pertumbuhan", lang: "id" },
  { text: "Bukan tentang di mana kamu berada sekarang, tapi ke mana kamu menuju.", author: "Anonimus", category: "Pertumbuhan", lang: "id" },
  { text: "Tantangan adalah cara alam semesta menanyakan apakah kamu serius dengan mimpimu.", author: "Anonimus", category: "Pertumbuhan", lang: "id" },
  { text: "Jadilah seperti air — beradaptasi dengan wadahnya, tapi tidak kehilangan sifat aslinya.", author: "Bruce Lee", category: "Pertumbuhan", lang: "id" },
  { text: "Setiap pengalaman mengajarkanmu sesuatu, bahkan yang terasa paling pahit sekalipun.", author: "Anonimus", category: "Pertumbuhan", lang: "id" },
  { text: "Seseorang yang berhenti belajar adalah seseorang yang sudah tua, entah ia berumur 20 atau 80 tahun.", author: "Henry Ford", category: "Pertumbuhan", lang: "id" },
  { text: "Tidak ada yang lebih berbahaya dari berhenti berkembang.", author: "Anonimus", category: "Pertumbuhan", lang: "id" },
  { text: "Kamu tumbuh ketika kamu berhenti pura-pura semuanya baik-baik saja dan mulai jujur dengan dirimu.", author: "Anonimus", category: "Pertumbuhan", lang: "id" },
  { text: "Masa lalumu bukan penjaramu — itu adalah tanah subur yang membuatmu tumbuh sampai di sini.", author: "Anonimus", category: "Pertumbuhan", lang: "id" },
  { text: "Jadilah orang yang kamu butuhkan ketika kamu masih kecil.", author: "Anonimus", category: "Pertumbuhan", lang: "id" },
  { text: "Setiap kali kamu melewati hal yang sulit, kamu meninggalkan versi dirimu yang lebih lemah di sana.", author: "Anonimus", category: "Pertumbuhan", lang: "id" },
  { text: "Ilmu adalah cahaya yang tidak pernah padam meski angin bertiup kencang.", author: "Anonimus", category: "Pertumbuhan", lang: "id" },
  { text: "Setiap bab baru dalam hidupmu membutuhkan menutup bab lama dengan penuh syukur.", author: "Anonimus", category: "Pertumbuhan", lang: "id" },
  { text: "Jangan hanya menghitung hari yang berlalu — buatlah setiap hari berarti.", author: "Anonimus", category: "Pertumbuhan", lang: "id" },
  { text: "Kamu tidak harus mengerti seluruh jalan — cukup tahu satu langkah selanjutnya.", author: "Anonimus", category: "Pertumbuhan", lang: "id" },
  { text: "Yang paling berani adalah yang berani mengubah dirinya sendiri.", author: "Anonimus", category: "Pertumbuhan", lang: "id" },
  { text: "وَقُل رَّبِّ زِدۡنِي عِلۡمٗا", author: "Q.S. Taha: 114", category: "Pertumbuhan", lang: "ar", translation: "Dan katakanlah: 'Ya Tuhanku, tambahkanlah kepadaku ilmu pengetahuan.'" },
  { text: "طَلَبُ الْعِلْمِ فَرِيضَةٌ عَلَى كُلِّ مُسْلِمٍ", author: "H.R. Ibnu Majah", category: "Pertumbuhan", lang: "ar", translation: "Menuntut ilmu adalah kewajiban bagi setiap Muslim." },
  { text: "خَيۡرُ ٱلنَّاسِ أَنفَعُهُمۡ لِلنَّاسِ", author: "H.R. Ahmad", category: "Pertumbuhan", lang: "ar", translation: "Sebaik-baik manusia adalah yang paling bermanfaat bagi manusia lainnya." },
  { text: "اِقۡرَأۡ بِٱسۡمِ رَبِّكَ ٱلَّذِي خَلَقَ", author: "Q.S. Al-Alaq: 1", category: "Pertumbuhan", lang: "ar", translation: "Bacalah dengan (menyebut) nama Tuhanmu Yang menciptakan." },
  { text: "أَلَا إِنَّمَا الْعِلْمُ بِالتَّعَلُّمِ", author: "Pepatah Arab", category: "Pertumbuhan", lang: "ar", translation: "Ketahuilah, sesungguhnya ilmu hanya diperoleh dengan belajar." },
  { text: "مَا تَعَلَّمَ الْعَبْدُ شَيْئًا أَفْضَلَ مِنَ التَّوَاضُعِ", author: "Pepatah Arab", category: "Pertumbuhan", lang: "ar", translation: "Tiada yang dipelajari seorang hamba yang lebih utama dari sifat rendah hati." },
  { text: "لَوْ كَانَ الْعِلْمُ بِالسَّمَاءِ لَنَالَهُ مَنْ يَطْلُبُهُ", author: "Pepatah Arab", category: "Pertumbuhan", lang: "ar", translation: "Seandainya ilmu berada di langit sekalipun, orang yang sungguh mencarinya pasti akan mendapatkannya." },
  { text: "Be not afraid of growing slowly, be afraid only of standing still.", author: "Chinese Proverb", category: "Pertumbuhan", lang: "en", translation: "Jangan takut tumbuh perlahan, hanya takutlah berhenti di tempat." },
  { text: "The only person you should try to be better than is the person you were yesterday.", author: "Anonimus", category: "Pertumbuhan", lang: "en", translation: "Satu-satunya orang yang harus kamu coba kalahkan adalah dirimu sendiri kemarin." },
  { text: "What got you here won't get you there.", author: "Marshall Goldsmith", category: "Pertumbuhan", lang: "en", translation: "Apa yang membawamu ke sini belum tentu membawamu ke sana." },
  { text: "Education is the most powerful weapon which you can use to change the world.", author: "Nelson Mandela", category: "Pertumbuhan", lang: "en", translation: "Pendidikan adalah senjata paling ampuh yang bisa kamu gunakan untuk mengubah dunia." },
  { text: "Growth is painful. Change is painful. But nothing is as painful as staying stuck somewhere you don't belong.", author: "Mandy Hale", category: "Pertumbuhan", lang: "en", translation: "Pertumbuhan itu menyakitkan. Perubahan pun demikian. Namun tidak ada yang lebih menyakitkan dari terjebak di tempat yang bukan milikmu." },
  { text: "Invest in yourself. Your career is the engine of your wealth.", author: "Paul Clitheroe", category: "Pertumbuhan", lang: "en", translation: "Investasikan pada dirimu. Kariermu adalah mesin kekayaanmu." },

  // ════════════════════════════════════════
  //  KARIR & PROFESIONAL (41 quotes)
  // ════════════════════════════════════════

  { text: "Konsisten kerjakan yang sudah kamu kerjakan, Fit, setiap hari adalah 1% improvement dalam hidupmu.", author: "Hendri", category: "Karir & Profesional", lang: "id" },
  { text: "Pekerjaan terbaik adalah pekerjaan yang membuatmu tumbuh, bukan hanya yang membuatmu nyaman.", author: "Anonimus", category: "Karir & Profesional", lang: "id" },
  { text: "Reputasi dibangun dari konsistensi, bukan dari kesempurnaan sesaat.", author: "Anonimus", category: "Karir & Profesional", lang: "id" },
  { text: "Kerja keras mengalahkan bakat ketika bakat tidak mau bekerja keras.", author: "Tim Notke", category: "Karir & Profesional", lang: "id" },
  { text: "Orang yang sukses tidak menunggu peluang — mereka menciptakannya.", author: "Anonimus", category: "Karir & Profesional", lang: "id" },
  { text: "Kualitas kerja adalah tanda penghormatan terbaik kepada dirimu sendiri.", author: "Anonimus", category: "Karir & Profesional", lang: "id" },
  { text: "Karir yang gemilang dimulai dari pekerjaan kecil yang dilakukan dengan luar biasa.", author: "Anonimus", category: "Karir & Profesional", lang: "id" },
  { text: "Jadilah seseorang yang tidak bisa diabaikan — bukan dengan keras kepala, tapi dengan keunggulan.", author: "Anonimus", category: "Karir & Profesional", lang: "id" },
  { text: "Setiap pengalaman kerja — termasuk yang pahit — adalah modal untuk perjalanan berikutnya.", author: "Anonimus", category: "Karir & Profesional", lang: "id" },
  { text: "Dedikasi adalah kerja yang kamu lakukan bahkan ketika tidak ada yang memperhatikan.", author: "Anonimus", category: "Karir & Profesional", lang: "id" },
  { text: "Profesionalisme bukan sekadar keahlian — itu adalah sikap yang kamu bawa ke setiap ruang.", author: "Anonimus", category: "Karir & Profesional", lang: "id" },
  { text: "Jangan kerja keras hanya untuk mendapat pujian. Kerja keras karena itu standar pribadimu.", author: "Anonimus", category: "Karir & Profesional", lang: "id" },
  { text: "Karir bukan perlombaan — itu adalah perjalanan menemukan di mana kontribusimu paling bermakna.", author: "Anonimus", category: "Karir & Profesional", lang: "id" },
  { text: "Yang membuat seseorang tak tergantikan bukan jabatannya, tapi dampak yang ia tinggalkan.", author: "Anonimus", category: "Karir & Profesional", lang: "id" },
  { text: "Kerjakan lebih dari yang diminta, pelajari lebih dari yang dibutuhkan.", author: "Anonimus", category: "Karir & Profesional", lang: "id" },
  { text: "Pintu kesempatan tidak terbuka untuk mereka yang hanya menunggu — tapi untuk mereka yang mengetuknya.", author: "Anonimus", category: "Karir & Profesional", lang: "id" },
  { text: "Kepercayaan dibangun satu tindakan dalam satu waktu.", author: "Anonimus", category: "Karir & Profesional", lang: "id" },
  { text: "Sukses bukan akhir tujuan — itu hanya bukti bahwa kamu telah berjalan dengan benar.", author: "Anonimus", category: "Karir & Profesional", lang: "id" },
  { text: "Orang paling sukses adalah mereka yang tidak pernah berhenti belajar dan tidak pernah berhenti berkarya.", author: "Anonimus", category: "Karir & Profesional", lang: "id" },
  { text: "Kerja dengan sepenuh hati. Alam semesta menghargai kesungguhan.", author: "Anonimus", category: "Karir & Profesional", lang: "id" },
  { text: "Biarkan pekerjaanmu berbicara lebih keras dari kata-katamu.", author: "Anonimus", category: "Karir & Profesional", lang: "id" },
  { text: "Tempat baru bukan pengkhianatan pada tempat lama — itu adalah kelanjutan dari perjalananmu.", author: "Anonimus", category: "Karir & Profesional", lang: "id" },
  { text: "Setiap keahlian yang kamu miliki hari ini adalah hasil dari waktu yang pernah kamu investasikan.", author: "Anonimus", category: "Karir & Profesional", lang: "id" },
  { text: "Kamu tidak meninggalkan tempat kerja — kamu membawa semua yang kamu pelajari ke tempat berikutnya.", author: "Anonimus", category: "Karir & Profesional", lang: "id" },
  { text: "Integritas dalam bekerja adalah investasi paling berharga yang tidak akan pernah kamu sesali.", author: "Anonimus", category: "Karir & Profesional", lang: "id" },
  { text: "Bekerja dengan passion bukan berarti tidak lelah — itu berarti lelahmu terasa bermakna.", author: "Anonimus", category: "Karir & Profesional", lang: "id" },
  { text: "Bukan gelar yang membuat seseorang dihormati, tapi cara ia bekerja dan berperilaku.", author: "Anonimus", category: "Karir & Profesional", lang: "id" },
  { text: "Jika kamu tidak suka apa yang kamu lakukan, ubah. Jika tidak bisa, ubah cara pandangmu.", author: "Wayne W. Dyer", category: "Karir & Profesional", lang: "id" },
  { text: "Yang paling baik dalam pekerjaannya adalah yang tidak pernah berhenti belajar tentang pekerjaannya.", author: "Anonimus", category: "Karir & Profesional", lang: "id" },
  { text: "إِنَّ اللَّهَ يُحِبُّ إِذَا عَمِلَ أَحَدُكُمْ عَمَلًا أَنْ يُتْقِنَهُ", author: "H.R. Baihaqi", category: "Karir & Profesional", lang: "ar", translation: "Sesungguhnya Allah mencintai jika salah seorang dari kalian mengerjakan suatu pekerjaan, ia mengerjakannya dengan sempurna (itqan)." },
  { text: "اعْمَلْ لِدُنْيَاكَ كَأَنَّكَ تَعِيشُ أَبَدًا وَاعْمَلْ لِآخِرَتِكَ كَأَنَّكَ تَمُوتُ غَدًا", author: "Pepatah Arab", category: "Karir & Profesional", lang: "ar", translation: "Bekerjalah untuk duniamu seolah kamu akan hidup selamanya, dan bekerjalah untuk akhiratmu seolah kamu akan mati besok." },
  { text: "وَأَن لَّيۡسَ لِلۡإِنسَٰنِ إِلَّا مَا سَعَىٰ", author: "Q.S. An-Najm: 39", category: "Karir & Profesional", lang: "ar", translation: "Dan bahwa manusia hanya memperoleh apa yang telah diusahakannya." },
  { text: "الْمَرْءُ يُعْرَفُ بِعَمَلِهِ لَا بِقَوْلِهِ", author: "Pepatah Arab", category: "Karir & Profesional", lang: "ar", translation: "Seseorang dikenal dari perbuatannya, bukan dari ucapannya." },
  { text: "أَتْقِنْ عَمَلَكَ تَكُنْ سَيِّدَ نَفْسِكَ", author: "Pepatah Arab", category: "Karir & Profesional", lang: "ar", translation: "Sempurnakanlah pekerjaanmu, maka kamu akan menjadi tuan atas dirimu sendiri." },
  { text: "Choose a job you love, and you will never have to work a day in your life.", author: "Confucius", category: "Karir & Profesional", lang: "en", translation: "Pilih pekerjaan yang kamu cintai, dan kamu tidak akan pernah benar-benar 'bekerja' seumur hidup." },
  { text: "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do great work.", author: "Steve Jobs", category: "Karir & Profesional", lang: "en", translation: "Pekerjaanmu akan mengisi sebagian besar hidupmu, dan satu-satunya cara untuk benar-benar puas adalah dengan melakukan pekerjaan yang luar biasa." },
  { text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson", category: "Karir & Profesional", lang: "en", translation: "Jangan memandangi jam; lakukan apa yang dilakukan jam. Terus bergerak." },
  { text: "Opportunities don't happen. You create them.", author: "Chris Grosser", category: "Karir & Profesional", lang: "en", translation: "Peluang tidak terjadi begitu saja. Kamu yang menciptakannya." },
  { text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau", category: "Karir & Profesional", lang: "en", translation: "Kesuksesan biasanya datang kepada mereka yang terlalu sibuk untuk mencarinya." },
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain", category: "Karir & Profesional", lang: "en", translation: "Rahasia untuk maju adalah memulai." },
  { text: "Hard work beats talent when talent doesn't work hard.", author: "Tim Notke", category: "Karir & Profesional", lang: "en", translation: "Kerja keras mengalahkan bakat ketika bakat tidak mau bekerja keras." },

  // ════════════════════════════════════════
  //  MIMPI (39 quotes)
  // ════════════════════════════════════════

  { text: "Fit, kamu pantas bermimpi besar dan memiliki realita besar!.", author: "Hendri", category: "Mimpi", lang: "id" },
  { text: "Mimpi tidak memiliki batas usia. Bermimpilah selagi masih bernapas.", author: "Anonimus", category: "Mimpi", lang: "id" },
  { text: "Mimpi yang besar dimulai dari satu langkah kecil.", author: "Anonimus", category: "Mimpi", lang: "id" },
  { text: "Jadikan mimpimu lebih besar dari ketakutanmu.", author: "Anonimus", category: "Mimpi", lang: "id" },
  { text: "Mimpi adalah kompas yang mengarahkan langkah-langkahmu.", author: "Anonimus", category: "Mimpi", lang: "id" },
  { text: "Tidak ada yang terlambat untuk memulai mengejar apa yang kamu inginkan.", author: "Anonimus", category: "Mimpi", lang: "id" },
  { text: "Mereka yang berhenti bermimpi adalah mereka yang mulai mati dari dalam.", author: "Anonimus", category: "Mimpi", lang: "id" },
  { text: "Mimpimu adalah cermin dari siapa dirimu yang sesungguhnya.", author: "Anonimus", category: "Mimpi", lang: "id" },
  { text: "Jangan biarkan mimpimu tetap menjadi mimpi.", author: "Anonimus", category: "Mimpi", lang: "id" },
  { text: "Kamu hanya sejauh yang berani kamu impikan.", author: "Anonimus", category: "Mimpi", lang: "id" },
  { text: "Impian yang jelas memberi kekuatan di hari-hari yang paling buram sekalipun.", author: "Anonimus", category: "Mimpi", lang: "id" },
  { text: "Bermimpilah besar. Mulailah kecil. Bertindaklah sekarang.", author: "Robin Sharma", category: "Mimpi", lang: "id" },
  { text: "Setiap perjalanan panjang dimulai dari satu langkah pertama.", author: "Lao Tzu", category: "Mimpi", lang: "id" },
  { text: "Bukan usia yang membatasi mimpimu — tapi keberanian untuk mewujudkannya.", author: "Anonimus", category: "Mimpi", lang: "id" },
  { text: "Mimpi tanpa tindakan hanyalah harapan. Tindakan tanpa mimpi hanyalah rutinitas.", author: "Anonimus", category: "Mimpi", lang: "id" },
  { text: "Yang membuatmu berbeda adalah berani percaya bahwa mimpimu layak untuk diperjuangkan.", author: "Anonimus", category: "Mimpi", lang: "id" },
  { text: "Kamu tidak perlu melihat seluruh anak tangga — cukup lihat anak tangga pertama.", author: "Martin Luther King Jr.", category: "Mimpi", lang: "id" },
  { text: "Dunia membutuhkan apa yang hanya bisa kamu tawarkan.", author: "Marie Forleo", category: "Mimpi", lang: "id" },
  { text: "Mimpi adalah bibit — tindakanlah airnya.", author: "Anonimus", category: "Mimpi", lang: "id" },
  { text: "Mimpimu tidak terlalu besar. Langkahmu hanya perlu lebih berani.", author: "Anonimus", category: "Mimpi", lang: "id" },
  { text: "Setiap orang yang berhasil pernah duduk di tempatmu dan bermimpi hal yang sama.", author: "Anonimus", category: "Mimpi", lang: "id" },
  { text: "Hidup terlalu singkat untuk tidak mengejar apa yang benar-benar membuatmu bersemangat.", author: "Anonimus", category: "Mimpi", lang: "id" },
  { text: "Satu-satunya batas yang nyata adalah batas yang kamu pasang sendiri.", author: "Napoleon Hill", category: "Mimpi", lang: "id" },
  { text: "Jangan hanya hidup di pinggiran mimpimu — masuklah ke tengahnya.", author: "Anonimus", category: "Mimpi", lang: "id" },
  { text: "Rencana tanpa aksi hanyalah mimpi. Aksi tanpa rencana hanyalah mimpi buruk.", author: "Pepatah Prancis", category: "Mimpi", lang: "id" },
  { text: "Orang yang bermimpi besar mungkin terlihat gila — sampai akhirnya mereka berhasil.", author: "Anonimus", category: "Mimpi", lang: "id" },
  { text: "Percayalah pada prosesmu. Setiap langkah menuju mimpimu itu nyata, meski belum terlihat.", author: "Anonimus", category: "Mimpi", lang: "id" },
  { text: "Mimpi terbesar adalah yang masih membuatmu bangun pagi dengan semangat.", author: "Anonimus", category: "Mimpi", lang: "id" },
  { text: "Mimpimu adalah portalmu ke masa depan yang bisa kamu pilih.", author: "Anonimus", category: "Mimpi", lang: "id" },
  { text: "إِنَّ اللَّهَ لَا يُغَيِّرُ مَا بِقَوۡمٍ حَتَّىٰ يُغَيِّرُوا مَا بِأَنفُسِهِمۡ", author: "Q.S. Ar-Ra'd: 11", category: "Mimpi", lang: "ar", translation: "Sesungguhnya Allah tidak mengubah keadaan suatu kaum sehingga mereka mengubah keadaan yang ada pada diri mereka sendiri." },
  { text: "اطْلُبُوا الْعِلْمَ وَلَوْ فِي الصِّينِ", author: "Pepatah Arab", category: "Mimpi", lang: "ar", translation: "Tuntutlah ilmu walau ke negeri Cina." },
  { text: "مَنِ اتَّقَى اللَّهَ وَجَدَ مَعَهُ مَخْرَجًا وَرَزَقَهُ مِنۡ حَيۡثُ لَا يَحۡتَسِبُ", author: "Q.S. Ath-Thalaq: 2-3", category: "Mimpi", lang: "ar", translation: "Barangsiapa bertakwa kepada Allah, niscaya Dia akan mengadakan jalan keluar baginya dan memberi rezeki dari arah yang tidak disangka-sangkanya." },
  { text: "بَلِّغُوا عَنِّي وَلَوْ آيَةً", author: "H.R. Bukhari", category: "Mimpi", lang: "ar", translation: "Sampaikanlah dariku walau satu ayat." },
  { text: "All our dreams can come true, if we have the courage to pursue them.", author: "Walt Disney", category: "Mimpi", lang: "en", translation: "Semua mimpi kita bisa menjadi kenyataan, jika kita punya keberanian untuk mengejarnya." },
  { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt", category: "Mimpi", lang: "en", translation: "Masa depan adalah milik mereka yang percaya akan keindahan impian-impiannya." },
  { text: "A dream doesn't become reality through magic; it takes sweat, determination and hard work.", author: "Colin Powell", category: "Mimpi", lang: "en", translation: "Mimpi tidak menjadi kenyataan lewat keajaiban; butuh keringat, keteguhan, dan kerja keras." },
  { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis", category: "Mimpi", lang: "en", translation: "Kamu tidak pernah terlalu tua untuk menetapkan tujuan baru atau memimpikan mimpi baru." },
  { text: "Hold fast to dreams, for if dreams die, life is a broken-winged bird that cannot fly.", author: "Langston Hughes", category: "Mimpi", lang: "en", translation: "Pegang teguh impianmu, sebab jika impian mati, hidup adalah burung berpatah sayap yang tak bisa terbang." },
  { text: "Dream big, start small, act now.", author: "Robin Sharma", category: "Mimpi", lang: "en", translation: "Impikan yang besar, mulai dari yang kecil, bertindak sekarang." },

  // ════════════════════════════════════════
  //  BERSYUKUR (39 quotes)
  // ════════════════════════════════════════

  { text: "Bagaimana kamu bisa tidak bersyukur ketika kamu menyadari hidupmu dikelilingi banyak orang baik yang peduli dan sayang padamu, Fit? Panjatkan syukur ya.", author: "Hendri", category: "Bersyukur", lang: "id" },
  { text: "Syukur mengubah apa yang kita miliki menjadi cukup.", author: "Melody Beattie", category: "Bersyukur", lang: "id" },
  { text: "Orang yang paling bahagia bukan yang memiliki segalanya, tapi yang bersyukur atas apa yang ada.", author: "Anonimus", category: "Bersyukur", lang: "id" },
  { text: "Mulailah hari dengan rasa syukur, dan hari itu sudah menjadi hari yang baik.", author: "Anonimus", category: "Bersyukur", lang: "id" },
  { text: "Setiap hari yang kamu jalani adalah anugerah yang tidak semua orang dapatkan.", author: "Anonimus", category: "Bersyukur", lang: "id" },
  { text: "Rasa syukur adalah ingatan hati atas semua kebaikan yang diterima.", author: "Anonimus", category: "Bersyukur", lang: "id" },
  { text: "Hal yang paling mudah dilupakan adalah hal yang paling perlu disyukuri.", author: "Anonimus", category: "Bersyukur", lang: "id" },
  { text: "Bersyukurlah atas bekas luka itu — artinya kamu pernah berjuang.", author: "Anonimus", category: "Bersyukur", lang: "id" },
  { text: "Ada jutaan alasan untuk bersyukur. Pilihlah satu, dan hari ini sudah lebih baik.", author: "Anonimus", category: "Bersyukur", lang: "id" },
  { text: "Kebahagiaan bukan soal mendapat lebih banyak — tapi soal menghargai yang sudah ada.", author: "Anonimus", category: "Bersyukur", lang: "id" },
  { text: "Ketika kamu bersyukur, ketakutan menghilang dan kelimpahan muncul.", author: "Anthony Robbins", category: "Bersyukur", lang: "id" },
  { text: "Syukur bukan hanya tentang kata-kata — itu tentang cara pandangmu terhadap hidup.", author: "Anonimus", category: "Bersyukur", lang: "id" },
  { text: "Setiap kesulitan membawa serta benih kesyukuran yang baru.", author: "Anonimus", category: "Bersyukur", lang: "id" },
  { text: "Hitung berkatmu, bukan masalahmu.", author: "Anonimus", category: "Bersyukur", lang: "id" },
  { text: "Seseorang yang penuh syukur jarang punya ruang untuk kebencian.", author: "Anonimus", category: "Bersyukur", lang: "id" },
  { text: "Bersyukurlah atas apa yang kamu punya, sambil terus bekerja untuk apa yang kamu inginkan.", author: "Anonimus", category: "Bersyukur", lang: "id" },
  { text: "Syukur bukan hanya ekspresi — itu adalah cara hidup.", author: "Anonimus", category: "Bersyukur", lang: "id" },
  { text: "Hal terbaik dalam hidupmu adalah hal-hal yang tidak bisa dibeli dengan uang.", author: "Anonimus", category: "Bersyukur", lang: "id" },
  { text: "Bersyukur atas perjalananmu, bukan hanya tujuannya.", author: "Anonimus", category: "Bersyukur", lang: "id" },
  { text: "Setiap detik yang kamu masih bisa bernapas adalah alasan yang cukup untuk bersyukur.", author: "Anonimus", category: "Bersyukur", lang: "id" },
  { text: "Nikmat terbesar seringkali yang paling tidak kita sadari.", author: "Anonimus", category: "Bersyukur", lang: "id" },
  { text: "Lihat ke belakang — betapa jauh perjalanan yang sudah kamu tempuh. Syukuri itu.", author: "Anonimus", category: "Bersyukur", lang: "id" },
  { text: "Ketenangan jiwa lahir dari rasa syukur yang tulus.", author: "Anonimus", category: "Bersyukur", lang: "id" },
  { text: "Jangan pernah terlalu sibuk untuk bersyukur.", author: "Anonimus", category: "Bersyukur", lang: "id" },
  { text: "Ketika kamu bersyukur untuk hal-hal kecil, hal-hal besar pun ikut terasa indah.", author: "Anonimus", category: "Bersyukur", lang: "id" },
  { text: "Kamu kaya ketika kamu mensyukuri apa yang dimiliki orang lain tidak mereka sadari.", author: "Anonimus", category: "Bersyukur", lang: "id" },
  { text: "لَئِن شَكَرۡتُمۡ لَأَزِيدَنَّكُمۡ", author: "Q.S. Ibrahim: 7", category: "Bersyukur", lang: "ar", translation: "Jika kalian bersyukur, niscaya Aku akan menambah nikmat kepada kalian." },
  { text: "الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ", author: "Q.S. Al-Fatihah: 2", category: "Bersyukur", lang: "ar", translation: "Segala puji hanya bagi Allah, Tuhan seluruh alam." },
  { text: "وَإِن تَعُدُّوا نِعۡمَتَ ٱللَّهِ لَا تُحۡصُوهَا", author: "Q.S. Ibrahim: 34", category: "Bersyukur", lang: "ar", translation: "Dan jika kamu menghitung nikmat Allah, niscaya kamu tidak akan mampu menghitungnya." },
  { text: "اللَّهُمَّ أَعِنِّي عَلَى ذِكْرِكَ وَشُكْرِكَ وَحُسْنِ عِبَادَتِكَ", author: "Doa Nabi, H.R. Abu Dawud", category: "Bersyukur", lang: "ar", translation: "Ya Allah, bantulah aku untuk selalu mengingat-Mu, bersyukur kepada-Mu, dan beribadah kepada-Mu dengan sebaik-baiknya." },
  { text: "مَنْ لَا يَشْكُرُ النَّاسَ لَا يَشْكُرُ اللَّهَ", author: "H.R. Abu Dawud", category: "Bersyukur", lang: "ar", translation: "Barangsiapa yang tidak bersyukur kepada manusia, maka ia tidak bersyukur kepada Allah." },
  { text: "الرِّضَا كَنْزٌ لَا يَفْنَى", author: "Pepatah Arab", category: "Bersyukur", lang: "ar", translation: "Keridhaan adalah harta yang tidak akan habis." },
  { text: "وَأَمَّا بِنِعۡمَةِ رَبِّكَ فَحَدِّثۡ", author: "Q.S. Adh-Dhuha: 11", category: "Bersyukur", lang: "ar", translation: "Dan terhadap nikmat Tuhanmu, maka hendaklah kamu menyebut-nyebutnya (bersyukur)." },
  { text: "نِعْمَتَانِ مَغْبُونٌ فِيهِمَا كَثِيرٌ مِنَ النَّاسِ: الصِّحَّةُ وَالْفَرَاغُ", author: "H.R. Bukhari", category: "Bersyukur", lang: "ar", translation: "Dua nikmat yang banyak orang merugi di dalamnya: kesehatan dan waktu luang." },
  { text: "تَفَكَّرُوا فِي آلَاءِ اللَّهِ وَلَا تَتَفَكَّرُوا فِي اللَّهِ", author: "Hadits", category: "Bersyukur", lang: "ar", translation: "Renungkanlah nikmat-nikmat Allah, dan janganlah merenungkan tentang Zat-Nya." },
  { text: "Gratitude is the healthiest of all human emotions.", author: "Zig Ziglar", category: "Bersyukur", lang: "en", translation: "Rasa syukur adalah emosi manusia yang paling menyehatkan." },
  { text: "Gratitude turns what we have into enough.", author: "Anonimus", category: "Bersyukur", lang: "en", translation: "Rasa syukur mengubah apa yang kita miliki menjadi cukup." },
  { text: "In ordinary life we hardly realize that we receive a great deal more than we give.", author: "Dietrich Bonhoeffer", category: "Bersyukur", lang: "en", translation: "Dalam kehidupan biasa kita hampir tidak menyadari bahwa kita menerima jauh lebih banyak daripada yang kita berikan." },

  // ════════════════════════════════════════
  //  CINTA & KASIH (39 quotes)
  // ════════════════════════════════════════

  { text: "Allah akan bukakan jalan untuk kamu bersama orang yang paling kau cinta dan paling mencintaimu.", author: "Hendri", category: "Cinta & Kasih", lang: "id" },
  { text: "Kasih sayang yang tulus tidak mengharapkan imbalan — ia memberikan karena itulah sifatnya.", author: "Anonimus", category: "Cinta & Kasih", lang: "id" },
  { text: "Mencintai dengan tulus adalah keberanian tertinggi yang dimiliki manusia.", author: "Anonimus", category: "Cinta & Kasih", lang: "id" },
  { text: "Kebaikan adalah bahasa yang bisa dimengerti oleh orang tuli dan dilihat oleh orang buta.", author: "Mark Twain", category: "Cinta & Kasih", lang: "id" },
  { text: "Senyum adalah hadiah paling murah yang bisa kamu berikan, tapi nilainya tidak ternilai bagi penerimanya.", author: "Anonimus", category: "Cinta & Kasih", lang: "id" },
  { text: "Satu tindakan kebaikan yang tulus lebih kuat dari seribu kata-kata yang indah.", author: "Anonimus", category: "Cinta & Kasih", lang: "id" },
  { text: "Dunia menjadi lebih indah ketika ada orang yang peduli tanpa mengharapkan balasan.", author: "Anonimus", category: "Cinta & Kasih", lang: "id" },
  { text: "Kamu tidak perlu menjadi kaya untuk berbagi — waktu, perhatian, dan ketulusan sudah cukup.", author: "Anonimus", category: "Cinta & Kasih", lang: "id" },
  { text: "Mereka yang menebarkan kasih sayang tidak pernah kehabisan.", author: "Anonimus", category: "Cinta & Kasih", lang: "id" },
  { text: "Satu kebaikan kecil bisa mengubah seluruh hari seseorang.", author: "Anonimus", category: "Cinta & Kasih", lang: "id" },
  { text: "Jadilah seseorang yang membuat orang lain merasa dilihat dan dihargai.", author: "Anonimus", category: "Cinta & Kasih", lang: "id" },
  { text: "Kebaikan bukan kelemahan — itu adalah kekuatan yang dipilih.", author: "Anonimus", category: "Cinta & Kasih", lang: "id" },
  { text: "Cinta yang sesungguhnya tidak hanya diucapkan — ia diwujudkan dalam tindakan kecil sehari-hari.", author: "Anonimus", category: "Cinta & Kasih", lang: "id" },
  { text: "Orang yang paling dicintai adalah yang paling banyak mencintai.", author: "Anonimus", category: "Cinta & Kasih", lang: "id" },
  { text: "Jangan tunggu orang lain memulai kebaikan — jadilah yang pertama.", author: "Anonimus", category: "Cinta & Kasih", lang: "id" },
  { text: "Setiap orang yang kamu temui sedang berjuang dengan sesuatu yang tidak kamu ketahui. Bersikaplah baik.", author: "Plato", category: "Cinta & Kasih", lang: "id" },
  { text: "Cinta sejati tidak berkurang saat dibagikan — ia justru bertambah.", author: "Anonimus", category: "Cinta & Kasih", lang: "id" },
  { text: "Kasih sayang adalah bahasa universal yang melampaui batas apapun.", author: "Anonimus", category: "Cinta & Kasih", lang: "id" },
  { text: "Perhatian kecilmu bisa menjadi cahaya besar bagi seseorang yang sedang dalam kegelapan.", author: "Anonimus", category: "Cinta & Kasih", lang: "id" },
  { text: "Ikhlas berarti memberi tanpa mengharapkan tepuk tangan.", author: "Anonimus", category: "Cinta & Kasih", lang: "id" },
  { text: "Yang paling berbekas adalah kebaikan yang diberikan saat orang lain tidak mengharapkannya.", author: "Anonimus", category: "Cinta & Kasih", lang: "id" },
  { text: "Hati yang baik adalah rumah paling nyaman untuk ditinggali.", author: "Anonimus", category: "Cinta & Kasih", lang: "id" },
  { text: "Beri dirimu izin untuk mencintai kehidupanmu apa adanya hari ini.", author: "Anonimus", category: "Cinta & Kasih", lang: "id" },
  { text: "Orang yang penuh kasih tidak pernah benar-benar sendirian.", author: "Anonimus", category: "Cinta & Kasih", lang: "id" },
  { text: "Cinta adalah keputusan yang dibuat setiap hari, bukan hanya perasaan yang datang dan pergi.", author: "Anonimus", category: "Cinta & Kasih", lang: "id" },
  { text: "Kebaikan yang kamu tanamkan hari ini akan berbuah di waktu yang tidak kamu duga.", author: "Anonimus", category: "Cinta & Kasih", lang: "id" },
  { text: "Jadilah cahaya yang tidak menunggu dipuji untuk bersinar.", author: "Anonimus", category: "Cinta & Kasih", lang: "id" },
  { text: "Cinta bukan soal menemukan orang sempurna, tapi melihat orang tidak sempurna dengan sempurna.", author: "Sam Keen", category: "Cinta & Kasih", lang: "id" },
  { text: "Dimana ada cinta yang tulus, di sana ada keajaiban yang sederhana.", author: "Anonimus", category: "Cinta & Kasih", lang: "id" },
  { text: "إِنَّ اللَّهَ رَفِيقٌ يُحِبُّ الرِّفْقَ فِي الْأَمْرِ كُلِّهِ", author: "H.R. Bukhari", category: "Cinta & Kasih", lang: "ar", translation: "Sesungguhnya Allah itu Maha Lembut dan mencintai kelembutan dalam segala urusan." },
  { text: "الرَّاحِمُونَ يَرْحَمُهُمُ الرَّحْمَٰنُ", author: "H.R. Abu Dawud", category: "Cinta & Kasih", lang: "ar", translation: "Orang-orang yang penyayang akan disayangi oleh Ar-Rahman (Allah Yang Maha Pengasih)." },
  { text: "وَتَعَاوَنُوا عَلَى ٱلۡبِرِّ وَٱلتَّقۡوَىٰ", author: "Q.S. Al-Maidah: 2", category: "Cinta & Kasih", lang: "ar", translation: "Dan tolong-menolonglah kamu dalam kebajikan dan ketakwaan." },
  { text: "لَا يُؤْمِنُ أَحَدُكُمْ حَتَّى يُحِبَّ لِأَخِيهِ مَا يُحِبُّ لِنَفْسِهِ", author: "H.R. Bukhari", category: "Cinta & Kasih", lang: "ar", translation: "Tidak sempurna iman salah seorang di antara kalian sampai ia mencintai untuk saudaranya apa yang ia cintai untuk dirinya sendiri." },
  { text: "خَيْرُكُمْ خَيْرُكُمْ لِأَهْلِهِ", author: "H.R. Tirmidzi", category: "Cinta & Kasih", lang: "ar", translation: "Sebaik-baik kamu adalah yang paling baik terhadap keluarganya." },
  { text: "إِنَّ اللَّهَ جَمِيلٌ يُحِبُّ الْجَمَالَ", author: "H.R. Muslim", category: "Cinta & Kasih", lang: "ar", translation: "Sesungguhnya Allah itu Maha Indah dan mencintai keindahan." },
  { text: "The best thing to hold onto in life is each other.", author: "Audrey Hepburn", category: "Cinta & Kasih", lang: "en", translation: "Hal terbaik untuk dipegang teguh dalam hidup adalah satu sama lain." },
  { text: "Kindness is the language which the deaf can hear and the blind can see.", author: "Mark Twain", category: "Cinta & Kasih", lang: "en", translation: "Kebaikan adalah bahasa yang bisa didengar oleh orang tuli dan dilihat oleh orang buta." },
  { text: "You can't live a perfect day without doing something for someone who will never be able to repay you.", author: "John Wooden", category: "Cinta & Kasih", lang: "en", translation: "Kamu tidak bisa menjalani hari yang sempurna tanpa melakukan sesuatu bagi seseorang yang tidak akan pernah bisa membalasmu." },

  // ════════════════════════════════════════
  //  KETENANGAN (39 quotes)
  // ════════════════════════════════════════

  { text: "Tidak usah buru-buru, ambil waktumu untuk mencari ketenangan Fit.", author: "Hendri", category: "Ketenangan", lang: "id" },
  { text: "Kedamaian tidak ditemukan di luar — ia selalu ada di dalam.", author: "Anonimus", category: "Ketenangan", lang: "id" },
  { text: "Letakkan kekhawatiranmu. Kamu tidak bisa mengendalikan segalanya, tapi kamu bisa memilih cara menghadapinya.", author: "Anonimus", category: "Ketenangan", lang: "id" },
  { text: "Nafas dalam-dalam adalah cara termudah untuk mengingatkan dirimu bahwa semuanya masih baik-baik saja.", author: "Anonimus", category: "Ketenangan", lang: "id" },
  { text: "Badai paling dahsyat pun pasti berlalu. Tugasmu adalah bertahan, bukan menghentikannya.", author: "Anonimus", category: "Ketenangan", lang: "id" },
  { text: "Jiwa yang tenang adalah jiwa yang tidak mudah diguncang oleh pendapat orang lain.", author: "Anonimus", category: "Ketenangan", lang: "id" },
  { text: "Ketika kamu tidak bisa mengubah situasi, ubah caramu menghadapinya.", author: "Viktor Frankl", category: "Ketenangan", lang: "id" },
  { text: "Ketenangan bukan soal tidak ada masalah — tapi soal damai di tengah masalah.", author: "Anonimus", category: "Ketenangan", lang: "id" },
  { text: "Kamu tidak perlu memiliki segalanya untuk merasa baik. Cukup hadir sepenuhnya di sini.", author: "Anonimus", category: "Ketenangan", lang: "id" },
  { text: "Tidak semua yang terasa berat memang seberat yang kita kira.", author: "Anonimus", category: "Ketenangan", lang: "id" },
  { text: "Serahkan apa yang di luar kendalimu. Fokus pada apa yang bisa kamu kendalikan.", author: "Anonimus", category: "Ketenangan", lang: "id" },
  { text: "Pikiran yang gelisah tidak akan menemukan jawaban — hati yang tenang akan.", author: "Anonimus", category: "Ketenangan", lang: "id" },
  { text: "Belajarlah untuk duduk dengan ketidakpastian tanpa perlu mengendalikannya.", author: "Anonimus", category: "Ketenangan", lang: "id" },
  { text: "Istirahat bukan kelemahan. Itu adalah bagian penting dari kekuatan.", author: "Anonimus", category: "Ketenangan", lang: "id" },
  { text: "Tidak ada yang lebih menenangkan dari menyadari bahwa kamu sudah cukup, apa adanya.", author: "Anonimus", category: "Ketenangan", lang: "id" },
  { text: "Kamu tidak harus kuat setiap waktu. Izinkan dirimu untuk beristirahat.", author: "Anonimus", category: "Ketenangan", lang: "id" },
  { text: "Lepaskan apa yang tidak lagi melayanimu. Tangan yang kosong siap menerima hal baru.", author: "Anonimus", category: "Ketenangan", lang: "id" },
  { text: "Menerima apa yang tidak bisa diubah adalah awal dari kedamaian sejati.", author: "Anonimus", category: "Ketenangan", lang: "id" },
  { text: "Air yang tenang tidak berarti tanpa kedalaman.", author: "Anonimus", category: "Ketenangan", lang: "id" },
  { text: "Dunia tidak perlu semua perhatianmu sekaligus. Satu hal dalam satu waktu.", author: "Anonimus", category: "Ketenangan", lang: "id" },
  { text: "Saat lelah, bukan berarti kamu lemah — itu artinya kamu sudah bekerja keras.", author: "Anonimus", category: "Ketenangan", lang: "id" },
  { text: "Percayalah bahwa semua yang terjadi padamu punya alasan yang indah.", author: "Anonimus", category: "Ketenangan", lang: "id" },
  { text: "Ketenangan jiwa dimulai dari berdamai dengan masa lalumu.", author: "Anonimus", category: "Ketenangan", lang: "id" },
  { text: "Jangan biarkan kebisingan dunia luar mengalahkan kesunyian damai di dalam dirimu.", author: "Anonimus", category: "Ketenangan", lang: "id" },
  { text: "Alam selalu mengembalikan kita pada kedamaian — pergilah ke alam saat hati sedang berat.", author: "Anonimus", category: "Ketenangan", lang: "id" },
  { text: "Kamu tidak perlu menjelaskan dirimu kepada semua orang. Cukup jadilah dirimu dengan tenang.", author: "Anonimus", category: "Ketenangan", lang: "id" },
  { text: "أَلَا بِذِكۡرِ ٱللَّهِ تَطۡمَئِنُّ ٱلۡقُلُوبُ", author: "Q.S. Ar-Ra'd: 28", category: "Ketenangan", lang: "ar", translation: "Ingatlah, hanya dengan mengingat Allah hati menjadi tenteram." },
  { text: "رَضِيتُ بِاللَّهِ رَبًّا وَبِالْإِسْلَامِ دِينًا وَبِمُحَمَّدٍ نَبِيًّا", author: "Doa Pagi-Petang", category: "Ketenangan", lang: "ar", translation: "Aku ridha Allah sebagai Tuhanku, Islam sebagai agamaku, dan Muhammad sebagai nabiku." },
  { text: "تَوَكَّلْ عَلَى اللَّهِ وَلَا تَعْجَزْ", author: "Pepatah Arab", category: "Ketenangan", lang: "ar", translation: "Bertawakallah kepada Allah dan janganlah kamu lemah." },
  { text: "قُلۡ لَّن يُصِيبَنَآ إِلَّا مَا كَتَبَ ٱللَّهُ لَنَا", author: "Q.S. At-Taubah: 51", category: "Ketenangan", lang: "ar", translation: "Katakanlah: Sekali-kali tidak akan menimpa kami melainkan apa yang telah ditetapkan Allah bagi kami." },
  { text: "الْقَنَاعَةُ كَنْزٌ لَا يَفْنَى", author: "Pepatah Arab", category: "Ketenangan", lang: "ar", translation: "Sifat qana'ah (merasa cukup) adalah harta yang tidak akan pernah habis." },
  { text: "حَسۡبِيَ ٱللَّهُ لَآ إِلَٰهَ إِلَّا هُوَ عَلَيۡهِ تَوَكَّلۡتُ", author: "Q.S. At-Taubah: 129", category: "Ketenangan", lang: "ar", translation: "Cukuplah Allah bagiku; tidak ada tuhan selain Dia. Hanya kepada-Nya aku bertawakal." },
  { text: "يَا أَيَّتُهَا ٱلنَّفۡسُ ٱلۡمُطۡمَئِنَّةُ ٱرۡجِعِيٓ إِلَىٰ رَبِّكِ رَاضِيَةٗ مَّرۡضِيَّةٗ", author: "Q.S. Al-Fajr: 27-28", category: "Ketenangan", lang: "ar", translation: "Hai jiwa yang tenang, kembalilah kepada Tuhanmu dengan hati yang ridha lagi diridhai-Nya." },
  { text: "وَٱلَّذِينَ ءَامَنُواْ وَعَمِلُواْ ٱلصَّٰلِحَٰتِ طُوبَىٰ لَهُمۡ", author: "Q.S. Ar-Ra'd: 29", category: "Ketenangan", lang: "ar", translation: "Dan orang-orang yang beriman dan mengerjakan kebajikan, bagi mereka kebahagiaan dan tempat kembali yang baik." },
  { text: "مَنۡ يَتَّقِ ٱللَّهَ يَجۡعَل لَّهُۥ مَخۡرَجٗا", author: "Q.S. Ath-Thalaq: 2", category: "Ketenangan", lang: "ar", translation: "Barangsiapa bertakwa kepada Allah, niscaya Allah akan memberi jalan keluar baginya." },
  { text: "You have power over your mind, not outside events. Realize this, and you will find strength.", author: "Marcus Aurelius", category: "Ketenangan", lang: "en", translation: "Kamu punya kuasa atas pikiranmu, bukan atas peristiwa di luar. Sadari ini, dan kamu akan menemukan kekuatan." },
  { text: "In the middle of every difficulty lies opportunity.", author: "Albert Einstein", category: "Ketenangan", lang: "en", translation: "Di tengah setiap kesulitan tersimpan sebuah kesempatan." },
  { text: "Peace is not the absence of conflict, it is the ability to handle conflict by peaceful means.", author: "Ronald Reagan", category: "Ketenangan", lang: "en", translation: "Kedamaian bukan ketiadaan konflik, melainkan kemampuan menghadapi konflik dengan cara yang damai." },

  // ════════════════════════════════════════
  //  PERSAHABATAN (42 quotes)
  // ════════════════════════════════════════

  { text: "Seumur hidup kamu akan dikelilingi orang-orang baik, dan seorang yang paling memahamimu. Trust me.", author: "Hendri", category: "Persahabatan", lang: "id" },
  { text: "Teman sejati adalah yang hadir saat semua orang telah pergi.", author: "Anonimus", category: "Persahabatan", lang: "id" },
  { text: "Persahabatan adalah jiwa yang hidup dalam dua raga.", author: "Aristoteles", category: "Persahabatan", lang: "id" },
  { text: "Satu teman yang jujur lebih berharga dari seribu teman yang menyenangkan.", author: "Anonimus", category: "Persahabatan", lang: "id" },
  { text: "Teman yang baik adalah cermin yang tidak berbohong.", author: "Anonimus", category: "Persahabatan", lang: "id" },
  { text: "Perjalanan jauh terasa dekat ketika ada teman yang menemani.", author: "Anonimus", category: "Persahabatan", lang: "id" },
  { text: "Kebersamaan adalah hal yang paling mahal yang tidak bisa dibeli.", author: "Anonimus", category: "Persahabatan", lang: "id" },
  { text: "Teman yang benar bukan yang membuatmu merasa sempurna, tapi yang membuatmu berani untuk tidak sempurna.", author: "Anonimus", category: "Persahabatan", lang: "id" },
  { text: "Persahabatan bukan soal berapa lama kamu mengenal seseorang, tapi seberapa dalam kamu mengenalnya.", author: "Anonimus", category: "Persahabatan", lang: "id" },
  { text: "Kesedihan dibagi dua menjadi setengahnya. Kebahagiaan dibagi dua menjadi dua kali lipat.", author: "Pepatah", category: "Persahabatan", lang: "id" },
  { text: "Bersyukurlah untuk setiap orang yang pernah menjadi bagian dari perjalananmu.", author: "Anonimus", category: "Persahabatan", lang: "id" },
  { text: "Ada orang yang datang ke hidupmu sebagai berkat. Ada yang datang sebagai pelajaran.", author: "Anonimus", category: "Persahabatan", lang: "id" },
  { text: "Teman yang baik tidak membuat segalanya sempurna — mereka membuatnya bermakna.", author: "Anonimus", category: "Persahabatan", lang: "id" },
  { text: "Lingkaran kecil yang tulus lebih baik dari lingkaran besar yang hampa.", author: "Anonimus", category: "Persahabatan", lang: "id" },
  { text: "Orang-orang terbaik dalam hidupmu adalah mereka yang membawa kebaikan tanpa diminta.", author: "Anonimus", category: "Persahabatan", lang: "id" },
  { text: "Sahabat sejati tidak menghitung jasa — mereka hanya hadir.", author: "Anonimus", category: "Persahabatan", lang: "id" },
  { text: "Kenangan indah bersama orang-orang terkasih adalah warisan yang tidak akan pernah habis.", author: "Anonimus", category: "Persahabatan", lang: "id" },
  { text: "Pertemanan yang bermakna dimulai dari keberanian untuk jujur.", author: "Anonimus", category: "Persahabatan", lang: "id" },
  { text: "Ada keajaiban dalam tertawa bersama — ia menyembuhkan hal-hal yang tidak bisa diobati kata-kata.", author: "Anonimus", category: "Persahabatan", lang: "id" },
  { text: "Teman baik adalah yang mengingatkanmu siapa dirimu di saat kamu lupa.", author: "Anonimus", category: "Persahabatan", lang: "id" },
  { text: "Tidak semua hubungan perlu bertahan selamanya untuk meninggalkan kesan yang abadi.", author: "Anonimus", category: "Persahabatan", lang: "id" },
  { text: "Jadilah teman yang ingin kamu miliki.", author: "Anonimus", category: "Persahabatan", lang: "id" },
  { text: "Kebersamaan yang singkat tapi tulus bisa meninggalkan jejak yang abadi.", author: "Anonimus", category: "Persahabatan", lang: "id" },
  { text: "Pertemuan bukan kebetulan — setiap orang yang masuk dalam hidupmu membawa pesan.", author: "Anonimus", category: "Persahabatan", lang: "id" },
  { text: "Bahkan ketika jauh, hati yang terhubung tidak pernah benar-benar berpisah.", author: "Anonimus", category: "Persahabatan", lang: "id" },
  { text: "Melepas dengan tulus adalah bentuk cinta tertinggi dalam persahabatan.", author: "Anonimus", category: "Persahabatan", lang: "id" },
  { text: "Teman terbaikmu adalah yang membuatmu tertawa paling keras dan menangis paling sedikit.", author: "Anonimus", category: "Persahabatan", lang: "id" },
  { text: "الْمَرْءُ عَلَى دِينِ خَلِيلِهِ فَلْيَنْظُرْ أَحَدُكُمْ مَنْ يُخَالِلُ", author: "H.R. Abu Dawud", category: "Persahabatan", lang: "ar", translation: "Seseorang itu mengikuti agama temannya, maka hendaklah salah seorang di antara kalian melihat dengan siapa ia berteman." },
  { text: "مَثَلُ الصَّدِيقِ الصَّالِحِ كَمَثَلِ الْعَطَّارِ", author: "H.R. Bukhari", category: "Persahabatan", lang: "ar", translation: "Perumpamaan teman yang baik adalah seperti penjual minyak wangi." },
  { text: "وَٱلۡمُؤۡمِنُونَ وَٱلۡمُؤۡمِنَٰتُ بَعۡضُهُمۡ أَوۡلِيَآءُ بَعۡضٍ", author: "Q.S. At-Taubah: 71", category: "Persahabatan", lang: "ar", translation: "Dan orang-orang yang beriman, laki-laki dan perempuan, sebagian mereka adalah menjadi penolong bagi sebagian yang lain." },
  { text: "مَنْ كَانَ فِي حَاجَةِ أَخِيهِ كَانَ اللَّهُ فِي حَاجَتِهِ", author: "H.R. Bukhari", category: "Persahabatan", lang: "ar", translation: "Barangsiapa membantu kebutuhan saudaranya, maka Allah akan membantu kebutuhannya." },
  { text: "إِنَّ مِنْ أَحَبِّكُمْ إِلَيَّ أَحْسَنَكُمْ أَخْلَاقًا", author: "H.R. Bukhari", category: "Persahabatan", lang: "ar", translation: "Sesungguhnya orang yang paling aku cintai di antara kalian adalah yang paling baik akhlaknya." },
  { text: "أَوْثَقُ عُرَى الإِيمَانِ: الْحُبُّ فِي اللَّهِ وَالْبُغْضُ فِي اللَّهِ", author: "H.R. Ahmad", category: "Persahabatan", lang: "ar", translation: "Tali iman yang paling kuat adalah cinta karena Allah dan benci karena Allah." },
  { text: "A friend is someone who knows all about you and still loves you.", author: "Elbert Hubbard", category: "Persahabatan", lang: "en", translation: "Teman adalah seseorang yang mengetahui segalanya tentangmu dan tetap mencintaimu." },
  { text: "Friendship is not about who you have known the longest, but who walked into your life and said 'I'm here for you.'", author: "Anonimus", category: "Persahabatan", lang: "en", translation: "Persahabatan bukan soal siapa yang paling lama kamu kenal, tapi siapa yang masuk dalam hidupmu dan berkata, 'Aku ada untukmu.'" },
  { text: "Walking with a friend in the dark is better than walking alone in the light.", author: "Helen Keller", category: "Persahabatan", lang: "en", translation: "Berjalan dengan teman dalam kegelapan lebih baik daripada berjalan sendirian dalam cahaya." },
  { text: "A real friend is one who walks in when the rest of the world walks out.", author: "Walter Winchell", category: "Persahabatan", lang: "en", translation: "Teman sejati adalah yang masuk ketika semua orang telah pergi." },
  { text: "Friends are the family we choose for ourselves.", author: "Edna Buchanan", category: "Persahabatan", lang: "en", translation: "Teman adalah keluarga yang kita pilih sendiri." },
  { text: "There's nothing like a really loyal, dependable, good friend. Nothing.", author: "Jennifer Aniston", category: "Persahabatan", lang: "en", translation: "Tidak ada yang sebanding dengan teman yang benar-benar setia, dapat diandalkan, dan baik. Tidak ada." },
  { text: "Friendship multiplies the good of life and divides the evil.", author: "Baltasar Gracian", category: "Persahabatan", lang: "en", translation: "Persahabatan melipatgandakan kebaikan dalam hidup dan membagi kejahatan." },
  { text: "In the cookie of life, friends are the chocolate chips.", author: "Salman Rushdie", category: "Persahabatan", lang: "en", translation: "Dalam kue kehidupan, teman adalah kepingan coklatnya." },
  { text: "True friendship comes when the silence between two people is comfortable.", author: "David Tyson", category: "Persahabatan", lang: "en", translation: "Persahabatan sejati datang ketika keheningan di antara dua orang terasa nyaman." },

];
